from tkinter import *

fenetre = Tk()


bouton0 = Checkbutton(fenetre, text="Le texte")
bouton0.pack()
bouton1 = Checkbutton(fenetre, text="Les boutons")
bouton1.pack()
bouton2 = Checkbutton(fenetre, text="Remettre tout le script")
bouton2.pack()
bouton3 = Checkbutton(fenetre, text="Les métiers")
bouton3.pack()
bouton4 = Checkbutton(fenetre, text="Les différent mondes")
bouton4.pack()
bouton5 = Checkbutton(fenetre, text="La déscription des métiers")
bouton5.pack()
bouton6 = Checkbutton(fenetre, text="La déscription des monstres")
bouton6.pack()
bouton7 = Checkbutton(fenetre, text="Disign du shop")
bouton7.pack()
bouton8 = Checkbutton(fenetre, text="Le Régler la plupart des problèmes")
bouton8.pack()
bouton9 = Checkbutton(fenetre, text="Mondes planétaires")
bouton9.pack()
bouton10 = Checkbutton(fenetre, text="Musique")
bouton10.pack()
bouton11 = Checkbutton(fenetre, text="E-mail idée amélioration")
bouton11.pack()
bouton12 = Checkbutton(fenetre, text="Max de HP (limite)")
bouton12.pack()
bouton13 = Checkbutton(fenetre, text="Barre de vie")
bouton13.pack()
bouton14 = Checkbutton(fenetre, text="Écris nombre d'attaque spéciale")
bouton14.pack()
bouton15 = Checkbutton(fenetre, text="Nouveau bouton : spécialité ((le feu, la glace...) nouvelle attaque.Tu peux l'utiliser 10 fois sauf si tu achète des boules de pouvoirs)")
bouton15.pack()
bouton16 = Checkbutton(fenetre, text="Écris nombre de spécialités")
bouton16.pack()
bouton17 = Checkbutton(fenetre, text="Vaisseau")
bouton17.pack()
bouton18 = Checkbutton(fenetre, text="Carte")
bouton18.pack()
bouton19 = Checkbutton(fenetre, text="Allié Flamant")
bouton19.pack()
bouton20 = Checkbutton(fenetre, text="Boutons attaque")
bouton20.pack()
bouton21 = Checkbutton(fenetre, text="Allié Loup disponible juste au monde 2")
bouton21.pack()
bouton22 = Checkbutton(fenetre, text="nouvel objet dans boutique : dc (les dc sont des attaques que tu peux apprendre)")
bouton22.pack()


fenetre.mainloop()